SimpleDateCalcApp/SimpleDateCalcApp/Models/AccountViewModels.cs
using System.ComponentModel.DataAnnotations;

namespace SimpleDateCalcApp.Models
{
    public class ExternalLoginConfirmationViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }
    }

    public class ManageUserViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class LoginViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }

    public class RegisterViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }
}

SimpleDateCalcApp/SimpleDateCalcApp/Models/IdentityModels.cs
using Microsoft.AspNet.Identity.EntityFramework;

namespace SimpleDateCalcApp.Models
{
    // You can add profile data for the user by adding more properties to your ApplicationUser class, please visit http://go.microsoft.com/fwlink/?LinkID=317594 to learn more.
    public class ApplicationUser : IdentityUser
    {
    }

    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDbContext()
            : base("DefaultConnection")
        {
        }
    }
}

SimpleDateCalcApp/SimpleDateCalcApp/Controllers/DateCalcController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using SimpleDateCalcApp.Shared;

namespace SimpleDateCalcApp.Controllers
{
    public class DateCalcController : Controller
    {
        //
        // GET: /DateCalc/
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string dateA, string dateB)
        {
            if (String.IsNullOrEmpty(dateA) || String.IsNullOrEmpty(dateB))
            {
                ViewBag.Error = "Please select 2 dates.";
                return View();
            }

            SimpleDate dA = new SimpleDate(dateA);
            SimpleDate dB = new SimpleDate(dateB);

            int dateDiff = dA - dB;
            ViewBag.DateDiff = String.Format("{0:0}", dateDiff);

            return View();
        }
	}
}

SimpleDateCalcApp/SimpleDateCalcApp/Views/DateCalc/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Date Calculator</h2>
<p class="lead">This app calculates how many days apart two given dates are.<br />Click on <em>Firt Date</em> and <em>Second Date</em> to select two dates and then click <em>Claculate Difference</em> to see the results.</p>

</p>@using (Html.BeginForm())
{
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.Label("dateA", "First Date (earlier date):")
                @Html.TextBox("dateA", null, new { @class = "form-control date-control", @style="cursor: text"})
            </div>
        </div>
        <div class="col-md-6">
            @Html.Label("dateB", "Second Date (later date):")
            @Html.TextBox("dateB", null, new { @class = "form-control date-control", @style="cursor: text" })
        </div>
    </div>
    if (ViewBag.Error != null)
    {
        <div class="row">
            <div class="col-md-12">
                @ViewBag.Error
            </div>
        </div>
    }
    if (ViewBag.DateDiff != null)
    {
        <div class="row">
            <div class="col-md-12">
                <h3>The two dates you've chosen are <b>@ViewBag.DateDiff</b> days apart.</h3>
            </div>
        </div>
    }
    <div class="row">
        <div class="col-md-1 text-center">
            <input type="submit" value="Calculate Difference" class="btn btn-lg btn-warning" />
        </div>
    </div>
}

@section scripts
{
    <script type="text/javascript">
        // Initialze date input fields with pick-a-date widget.
        $('.date-control').pickadate({format:'yyyy/mm/dd'});
    </script>
}

SimpleDateCalcApp/SimpleDateCalcApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Simple Date Calc App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Simple Date Calc App", "Index", "DateCalc", null, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>A <a href="http://www.twitter.com/HappyGezim">@@HappyGezim</a> production.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/pickadate")
    @RenderSection("scripts", required: false)
</body>
</html>